services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=disasterdb
    ports:
      - '5432:5432'
    volumes:
    - db:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  api:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=disasterdb;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=redis:6379


volumes:
  db:
    driver: local